/**
 * Advanced Configuration for Code Review Assistant
 * 
 * This file shows how to customize the review behavior.
 * Copy this to config.js and modify as needed.
 */

export const reviewConfig = {
  // GitHub Configuration
  github: {
    // Maximum number of files to review in detail
    maxFilesPerReview: 20,
    
    // File patterns to exclude from review
    excludePatterns: [
      'package-lock.json',
      'yarn.lock',
      '*.min.js',
      '*.map',
      'dist/**',
      'build/**',
      'node_modules/**'
    ],
    
    // File patterns to prioritize in review
    priorityPatterns: [
      'src/**/*.js',
      'src/**/*.ts',
      'lib/**/*.py'
    ]
  },

  // AI Review Configuration
  ai: {
    // OpenAI model to use
    model: 'gpt-4',
    
    // Temperature for AI responses (0-1, lower = more focused)
    temperature: 0.3,
    
    // Maximum tokens for AI response
    maxTokens: 2000,
    
    // Custom system prompt
    systemPrompt: `You are an expert code reviewer. Analyze the provided code changes and provide constructive feedback focusing on:
- Code quality and best practices
- Potential bugs or issues
- Security vulnerabilities
- Performance concerns
- Code maintainability
- Documentation and comments
- Test coverage

Provide specific, actionable feedback with line references where applicable.`
  },

  // Review Focus Areas
  focus: {
    // Enable/disable specific review aspects
    security: true,
    performance: true,
    maintainability: true,
    testing: true,
    documentation: true,
    style: true,
    
    // Severity levels to report (critical, high, medium, low)
    minSeverity: 'low',
    
    // Custom rules
    customRules: [
      {
        name: 'no-console-log',
        pattern: /console\.log/,
        message: 'Remove console.log statements before merging',
        severity: 'medium'
      },
      {
        name: 'no-todo-comments',
        pattern: /\/\/\s*TODO/i,
        message: 'TODO comments should be converted to issues',
        severity: 'low'
      }
    ]
  },

  // Comment Formatting
  formatting: {
    // Use emoji in comments
    useEmoji: true,
    
    // Include code snippets in comments
    includeSnippets: true,
    
    // Maximum length of code snippets
    maxSnippetLength: 100,
    
    // Comment template
    template: {
      header: '## 🤖 Automated Code Review',
      footer: '*This review was automatically generated by the Code Review Assistant.*'
    }
  },

  // Notification Settings
  notifications: {
    // Post summary comment
    postSummary: true,
    
    // Post detailed file comments
    postFileComments: false,
    
    // Mention PR author in critical issues
    mentionAuthorOnCritical: false
  },

  // Rate Limiting
  rateLimiting: {
    // Delay between API calls (ms)
    delayBetweenCalls: 1000,
    
    // Maximum retries on failure
    maxRetries: 3,
    
    // Retry delay (ms)
    retryDelay: 5000
  }
};

export default reviewConfig;

// Made with Bob
